[phases.setup]
nixPkgs = ["go"]

[phases.install]
cmds = ["cd backend && go mod download"]
workDir = "."

[phases.build]
cmds = ["cd backend && CGO_ENABLED=0 go build -o nexusacg ./cmd/server"]

[start]
cmd = "./backend/nexusacg"
